let { bech32 } = require('bech32') 

const decode = bech32.decode('cosmos1ntt549k3e2wj0732tve8uszh3ac3ekee49xmtt')
const akashAddr = bech32.encode('akash', decode.words)  
const axelarAddr = bech32.encode('axelar', decode.words)
const bandAddr = bech32.encode('band', decode.words)  
const bcnaAddr = bech32.encode('bcna', decode.words)
const bitsongAddr = bech32.encode('bitsong', decode.words)  
const cerberusAddr = bech32.encode('cerberus', decode.words)  
const certikAddr = bech32.encode('certik', decode.words)  
const chihuahuaAddr = bech32.encode('chihuahua', decode.words)
const comdexAddr = bech32.encode('comdex', decode.words)
const cosmosAddr = bech32.encode('cosmos', decode.words)
const crestAddr = bech32.encode('cre', decode.words)
const croAddr = bech32.encode('cro', decode.words)  
const c4etAddr = bech32.encode('c4e', decode.words)
const darcAddr = bech32.encode('darc', decode.words)  
const decentrAddr = bech32.encode('decentr', decode.words)
const desmosAddr = bech32.encode('desmos', decode.words)  
const digAddr = bech32.encode('dig', decode.words)
const emoneyAddr = bech32.encode('emoney', decode.words)  
const evmosAddr = bech32.encode('evmos', decode.words)  
const fetchAddr = bech32.encode('fetch', decode.words)  
const galaxyAddr = bech32.encode('galaxy', decode.words)
const gravityAddr = bech32.encode('gravity', decode.words)
const idepAddr = bech32.encode('idep', decode.words)  
const ivaAddr = bech32.encode('iva', decode.words)
const injAddr = bech32.encode('inj', decode.words)
const ixoAddr = bech32.encode('ixo', decode.words)
const junoAddr = bech32.encode('juno', decode.words)
const kavaAddr = bech32.encode('kava', decode.words)  
const kiAddr = bech32.encode('ki', decode.words)
const kujiraAddr = bech32.encode('kujira', decode.words)  
const lumAddr = bech32.encode('lum', decode.words)
const mantleAddr = bech32.encode('mantle', decode.words)  
const memeAddr = bech32.encode('meme', decode.words)  
const nomicAddr = bech32.encode('nomic', decode.words)  
const omniflixAddr = bech32.encode('omniflix', decode.words)
const oraiAddr = bech32.encode('orai', decode.words)
const osmosAddr = bech32.encode('osmo', decode.words)
const panaceaAddr = bech32.encode('panacea', decode.words)  
const pasgAddr = bech32.encode('pasg', decode.words)
const persistenceAddr = bech32.encode('persistence', decode.words)  
const rebusAddr = bech32.encode('rebus', decode.words)
const regenAddr = bech32.encode('regen', decode.words)  
const rizonAddr = bech32.encode('rizon', decode.words)  
const secretAddr = bech32.encode('secret', decode.words)  
const sentAddr = bech32.encode('sent', decode.words)
const sifAddr = bech32.encode('sif', decode.words)
const sommAddr = bech32.encode('somm', decode.words)  
const stafiAddr = bech32.encode('stafi', decode.words) 
const starsAddr = bech32.encode('stars', decode.words)
const starAddr = bech32.encode('star', decode.words)
const strideAddr = bech32.encode('stride', decode.words)
const tgradeAddr = bech32.encode('tgrade', decode.words) 
const toriAddr = bech32.encode('tori', decode.words)  
const umeeAddr = bech32.encode('umee', decode.words)

console.log(akashAddr)
console.log(axelarAddr)
console.log(bandAddr)
console.log(bcnaAddr)
console.log(bitsongAddr)
console.log(cerberusAddr)
console.log(certikAddr)
console.log(chihuahuaAddr)
console.log(comdexAddr)
console.log(cosmosAddr)
console.log(crestAddr)
console.log(croAddr)
console.log(c4eAddr)
console.log(darcAddr)
console.log(decentrAddr)
console.log(desmosAddr)
console.log(digAddr)
console.log(emoneyAddr)
console.log(evmosAddr)
console.log(fetchAddr)
console.log(galaxyAddr)
console.log(gravityAddr)
console.log(idepAddr)
console.log(ivaAddr)
console.log(injAddr)
console.log(ixoAddr)
console.log(junoAddr)
console.log(kavaAddr)
console.log(kiAddr)
console.log(kujiraAddr)
console.log(lumAddr)
console.log(mantleAddr)
console.log(memeAddr)
console.log(nomicAddr)
console.log(omniflixAddr)
console.log(oraiAddr)
console.log(osmosAddr)
console.log(panaceaAddr)
console.log(pasgAddr)
console.log(persistenceAddr)
console.log(rebusAddr)
console.log(regenAddr)
console.log(rizonAddr)
console.log(secretAddr)
console.log(sentAddr)
console.log(sifAddr)
console.log(sommAddr)
console.log(starsAddr)
console.log(starAddr)
console.log(strideAddr)
console.log(tgradeAddr)
console.log(toriAddr)
console.log(umeeAddr)
