let { bech32 } = require('bech32') 

const decode = bech32.decode('cosmos1ntt549k3e2wj0732tve8uszh3ac3ekee49xmtt')
const bcnaAddr = bech32.encode('bcna', decode.words)
const osmosAddr = bech32.encode('osmo', decode.words)
const cosmosAddr = bech32.encode('cosmos', decode.words)
const starsAddr = bech32.encode('stars', decode.words)
const junoAddr = bech32.encode('juno', decode.words)
const comdexAddr = bech32.encode('comdex', decode.words)
const chihuahuaAddr = bech32.encode('chihuahua', decode.words)
const cerberusAddr = bech32.encode('cerberus', decode.words)  
const akashAddr = bech32.encode('akash', decode.words)  
const axelarAddr = bech32.encode('axelar', decode.words)
const bitsongAddr = bech32.encode('bitsong', decode.words)  
const cryptoOrgAddr = bech32.encode('cro', decode.words)  
const certikAddr = bech32.encode('certik', decode.words)  

console.log(bcnaAddr)
console.log(osmosAddr)
console.log(cosmosAddr)
console.log(starsAddr)
console.log(comdexAddr)
console.log(chihuahuaAddr)
console.log(cerberusAddr)
console.log(akashAddr)
console.log(axelarAddr)
console.log(bitsongAddr)
console.log(cryptoOrgAddr)
console.log(certikAddr)
